### ISSUE TITLE
Terrible code

### ISSUE THREAD

**Issue by shawlaf** [Sk1er/nonbegon#1]

**Comment by Sk1er** [comment]
fixed

**Comment by shawlaf** [comment]
no mate:

https://github.com/Sk1er/nonbegon/blob/master/main/java/club/sk1er/mods/nonbegon/NonListener.java#L14 Naming conventions

https://github.com/Sk1er/nonbegon/blob/master/main/java/club/sk1er/mods/nonbegon/NonListener.java#L37

Can be replaced with:
```
Hypixel = FMLClientHandler.instance().getClient().getCurrentServerData().serverIP.contains(".hypixel.net") || FMLClientHandler.instance().getClient().getCurrentServerData().serverName.equalsIgnoreCase("HYPIXEL");
```

Fix it, nerd

**Comment by shawlaf** [comment]
Atleast i can get a basic socket to work instantly

**Comment by Sk1er** [comment]
I took that code from @MindMC xd

**Comment by inventor02** [comment]
cOPyInG cODe Oh DEaR yoUNG mAN
